services:
  theatre-db:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${SQL_DB}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - PGPORT=${SQL_PORT}
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql

  elastic:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

  etl:
    build: postgres_to_es
    env_file:
      - .env
    depends_on:
      - elastic
      - theatre-db

volumes:
  esdata:
  pgdata: